config/routes.rb
Rails.application.routes.draw do

  root 'products#index'
  resources :products, :only => [:index, :new, :create, :edit, :update, :destroy]

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_and_belongs_to_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_and_belongs_to_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def index
	  @products = Product.all

	end
	 
	def new
	  @product = Product.new
	end

	def create
	  @product = Product.new(product_params)
	  if @product.save
	  	redirect_to products_path, notice: "El producto fue publicado con éxito"
	  else
	  	render :index
	  end
		
	end
    
    def edit
     @product = Product.find(params[:id])
    end

    def update
     @product = Product.find(params[:id])
     if @product.update(product_params)
       redirect_to products_path, notice: "El producto fue modificado con éxito"
     else
     	render :edit
     end
    	
    end

    def destroy
      product = Product.find(params[:id])
      product.destroy
      redirect_to products_path, notice: "El producto fue eliminado con éxito"
    end

	private
    def product_params
      params.required(:product).permit(:name, :price, category_ids:[])
    	
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def form_title
    @product.new_record? ? "Publicar Producto" : "Modificar Producto"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProductsApps</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash[:notice]%>
  <div class="alert alert-info"><%= flash[:notice] %></div>
<% end %>
<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
 	  <h1><%= form_title %></h1>
 	  <%= form_for @product do |product|%>
 	    <div class="form-group">
 	      <%= product.text_field :name, class:"form-control input-lg", placeholder: "Producto"%>
 	    </div>
 	    <div class="form-group">
 	      <%= product.text_field :price, class:"form-control input-lg", placeholder:"Precio"%>
 	    </div>

      <%= product.collection_check_boxes :category_ids, Category.all, :id, :name do |c| %>
       <div class="checkbox">
         <%= c.label do %>
          <%= c.check_box %> <%= c.object.name %>
         <% end %>
       </div>
      <% end %>

 	    <div>
 	      <%= product.submit form_title, class: "btn btn-primary btn-lg btn-block"%>
 	    </div>
 	  <% end %>
    	
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<%= render 'form' %>

app/views/products/index.html.erb
<div class="container">
  <div class="row">
  	<div class="col-sm-8 col-sm-offset-2">
  	  <h1>Productos</h1>
  	  <%= link_to "Nuevo Producto", new_product_path, class: "btn btn-primary pull-right " %>
  	  <table class="table table-hover">
  	  	<thead>
  	      <tr>
  	        <th>Nombre</th>
  	        <th>Precio</th>
  	        <th>Categorías</th>
  	        <th></th>
  	        <th></th>
  	      </tr>
  	  	</thead>
  	  	<tbody>
  	  		<% @products.each do |product|%>
            <tr>
              <td><%= product.name %></td>
              <td><%= number_to_currency(product.price, precision:0) %> </td>
              <td><%= product.categories.pluck(:name).join(", ") %></td>
              <td><%= link_to "Editar", edit_product_path(product)%></td>
              <td><%= link_to "Eliminar", product_path(product), method: :delete%></td>
            </tr>
          <% end %>
  	  	</tbody>
  	  </table>
  	</div>
  </div>
</div>

app/views/products/new.html.erb
<%= render 'form' %>